name: Auto Update PR
on:
  push:
    branches:
      - main
jobs:
  autoupdate:
    name: Auto Update PR
    runs-on: ubuntu-latest
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
